---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "6750 Egremont Drive"
keywords:    "House for Sale, House 4 Sale, Real Estate, London, For Sale by Owner, Home"
description: "6750 Egremont Drive, Melrose Ontario"
source_link: "https://github.com/astallae/house4Sale"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  tropiteal: '#00A8C6'
  tealdrop:	 '#40C0CB'
  whitetrash: '#F9F2E7'
  atomicbikini: '#AEE239'
  feebleweek: '#8FBE00'
